<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="reposense.report.RepoClonerTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2024-01-18T13:20:36" hostname="TOP-WASHING-POW" time="10.689">
  <properties/>
  <testcase name="repoCloner_emptyRepo_failsGracefully()" classname="reposense.report.RepoClonerTest" time="5.496"/>
  <testcase name="repoCloner_validRepoLocationWithRelativePathingAndSpaces_success()" classname="reposense.report.RepoClonerTest" time="5.191"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[09:20:36 - Cloning in parallel from https://github.com/reposense/testrepo-Empty.git...
09:20:37 - Waiting for cloning of https://github.com/reposense/testrepo-Empty.git to complete...
09:20:39 - Cloning of https://github.com/reposense/testrepo-Empty.git completed!
09:20:40 - Cloning completed!
09:20:40 - Cloning completed!
09:20:41 - Cloning completed!
09:20:41 - Cloning completed!
09:20:41 - ?[43;30m[WARNING]?[m Exception met while trying to get current branch of https://github.com/reposense/testrepo-Empty.git (HEAD), will skip this repo.
09:20:41 - Cloning completed!
09:20:41 - Cloning completed!
09:20:41 - Cloning completed!
]]></system-err>
</testsuite>
